export const ElectronicItems = [
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    officialProductUrl: '',
    disabled: false
  },
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categories: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
];
