export const ElectronicItems = [
  {
    category: 'Electronics',
    key: '0001',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    officialProductUrl: '',
    disabled: false
  },
  {
    category: 'Electronics',
    key: '0002',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    key: '0003',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    key: '0004',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    key: '0005',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
  {
    category: 'Electronics',
    key: '0006',
    title: 'SonicGear Pandora Neo 500',
    subtitle: '',
    categoryTags: ['Bluetooth', 'Speakers', 'FM Radio'],
    popularTags: ['Useful', 'Multi-Usage', 'Compact'],
    styleTags: ['Simple', 'Stylish'],
    placeTags: ['Picnic', 'Studio'],
    dailyRental: 1.00,
    imageMainUrl: '0001.jpg',
    imageSubUrl: [],
    disabled: false
  },
];
